### ISSUE TITLE
Python cli code

### ISSUE THREAD

**Issue by Solana0x** [YunzhiYike/nodepay#1]
Hi can you make a normal python based CLI code? that can be easily used? i amgetting received 1011 (internal error); then sent 1011 (internal error)

error in my python script ..

**Comment by YunzhiYike** [comment]
You need update version

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/03/2024 17:16 |
| To | YunzhiYike/nodepay ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [YunzhiYike/nodepay] Python cli code (Issue #1) |

Hi can you make a normal python based CLI code? that can be easily used? i amgetting received 1011 (internal error); then sent 1011 (internal error)

error in my python script ..

**Comment by YunzhiYike** [comment]
The python version will be considered for support later on

**Comment by Solana0x** [comment]
you can check my grass repo and get the idea from there i almost made it just having received 1011 (internal error); then sent 1011 (internal error)

error

**Comment by YunzhiYike** [comment]
I don't understand. Are you having problems with nodepay or with grass now

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/03/2024 18:36 |
| To | YunzhiYike/nodepay ***@***.***> |
| Cc | 云知易客 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [YunzhiYike/nodepay] Python cli code (Issue #1) |

you can check my grass repo and get the idea from there i almost made it just having received 1011 (internal error); then sent 1011 (internal error)

error

**Comment by Solana0x** [comment]
i am having problem with the Nodepay

**Comment by YunzhiYike** [comment]
Post the question.

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/03/2024 22:59 |
| To | YunzhiYike/nodepay ***@***.***> |
| Cc | 云知易客 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [YunzhiYike/nodepay] Python cli code (Issue #1) |

i am having problem with the Nodepay
