### ISSUE TITLE
help me check error ?

### ISSUE THREAD

**Issue by ruanling** [YunzhiYike/nodepay#2]
![image](https://github.com/YunzhiYike/nodepay/assets/33116879/4382175d-60be-444c-a60a-dcd7823d4d30)
I get this error when running, can you help me check?

**Comment by YunzhiYike** [comment]
OK send your error log

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/07/2024 22:39 |
| To | YunzhiYike/nodepay ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [YunzhiYike/nodepay] help me check error ? (Issue #2) |

image.png (view on web)
I get this error when running, can you help me check?

**Comment by ruanling** [comment]
```
panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.getAccounts()
        /Users/songjun/project/go/nodepay/main.go:187 +0x945
main.main()
        /Users/songjun/project/go/nodepay/main.go:55 +0x2ea
```

**Comment by YunzhiYike** [comment]
check your cookies.txt file

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/07/2024 22:42 |
| To | YunzhiYike/nodepay ***@***.***> |
| Cc | 云知易客 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [YunzhiYike/nodepay] help me check error ? (Issue #2) |

panic: runtime error: index out of range [2] with length 2

goroutine 1 [running]:
main.getAccounts()
        /Users/songjun/project/go/nodepay/main.go:187 +0x945
main.main()
        /Users/songjun/project/go/nodepay/main.go:55 +0x2ea

**Comment by ruanling** [comment]
![image](https://github.com/YunzhiYike/nodepay/assets/33116879/47cb6759-6bfc-493b-999e-a7539ce43d76)

**Comment by YunzhiYike** [comment]
Check to see if there's a carriage return.

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/07/2024 22:47 |
| To | YunzhiYike/nodepay ***@***.***> |
| Cc | 云知易客 ***@***.***>,
Comment ***@***.***> |
| Subject | Re: [YunzhiYike/nodepay] help me check error ? (Issue #2) |

image.png (view on web)
