### ISSUE TITLE
Unable to keep connected

### ISSUE THREAD

**Issue by myzeling** [YunzhiYike/nodepay#3]
Is there something in the code to make the program connect to service automatically? I've met the problem that it just 2-3 hours and then run out of work for many times

**Comment by YunzhiYike** [comment]
Reconnections are caused by dynamic IP updates or disconnections from the Nodepay platform.

---- Replied Message ----
| From | ***@***.***> |
| Date | 06/13/2024 11:56 |
| To | YunzhiYike/nodepay ***@***.***> |
| Cc | Subscribed ***@***.***> |
| Subject | [YunzhiYike/nodepay] Unable to keep connected (Issue #3) |

Is there something in the code to make the program connect to service automatically? I've met the problem that it just 2-3 hours and then run out of work for many times

**Comment by myzeling** [comment]
> Reconnections are caused by dynamic IP updates or disconnections from the Nodepay platform.
> […](#)
> ---- Replied Message ---- | From | ***@***.***> | | Date | 06/13/2024 11:56 | | To | YunzhiYike/nodepay ***@***.***> | | Cc | Subscribed ***@***.***> | | Subject | [YunzhiYike/nodepay] Unable to keep connected (Issue #3) | Is there something in the code to make the program connect to service automatically? I've met the problem that it just 2-3 hours and then run out of work for many times — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>

My IPs are not dynamic ones. I suppose the reason is the latter. Everytime I met such situation, I need to run the exe again. So, I'am wondering, maybe the program can  be updated to restart when this problem happen again?

**Comment by YunzhiYike** [comment]
Re-connections may occur due to 1, client network instability (proxy IP or local network) 2, nodepay platform instability

**Comment by myzeling** [comment]
> Re-connections may occur due to 1, client network instability (proxy IP or local network) 2, nodepay platform instability

yeah, u are right, my local network is not so stable. So the only way to solve my problem is to restart the exe by my hand?

**Comment by YunzhiYike** [comment]
> > Re-connections may occur due to 1, client network instability (proxy IP or local network) 2, nodepay platform instability
> 
> yeah, u are right, my local network is not so stable. So the only way to solve my problem is to restart the exe by my hand?

set config.yml retry value to -1
