### ISSUE TITLE
Https supported?

### ISSUE THREAD

**Issue by myzeling** [YunzhiYike/nodepay#4]
I've tried some Http proxies and found that it worked out. So, I'm wondering if http proxies can be added to the proxy.txt beside socks5?

**Comment by YunzhiYike** [comment]
Only sk5 is supported

**Comment by YunzhiYike** [comment]
You can try to use http/https proxy

**Comment by myzeling** [comment]
> You can try to use http/https proxy

you mean that just add it to the proxy.txt?

**Comment by YunzhiYike** [comment]
yes
